"""change weather_year to string nullable for TMY support

Revision ID: 4a55fe96bebe
Revises: b2c3d4e5f6a7
Create Date: 2026-03-19 14:40:43.380429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a55fe96bebe'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runs', 'weather_year',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('runs', 'weather_year',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
