"""initial schema

Revision ID: 7f83e962a6cf
Revises: 
Create Date: 2026-03-07 17:37:39.118771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f83e962a6cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('run_name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('git_hash', sa.String(), nullable=True),
    sa.Column('data_sources', sa.String(), nullable=True),
    sa.Column('weather_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('run_inputs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('bess_dispatch_required', sa.Float(), nullable=True),
    sa.Column('bess_optimization_required', sa.Float(), nullable=True),
    sa.Column('dc_size_mw', sa.Float(), nullable=False),
    sa.Column('ac_installed_mw', sa.Float(), nullable=False),
    sa.Column('ac_poi_mw', sa.Float(), nullable=False),
    sa.Column('racking', sa.String(), nullable=False),
    sa.Column('tilt', sa.Float(), nullable=False),
    sa.Column('azimuth', sa.Float(), nullable=False),
    sa.Column('module_orientation', sa.String(), nullable=False),
    sa.Column('number_of_modules', sa.Integer(), nullable=False),
    sa.Column('ground_clearance_height_m', sa.Float(), nullable=False),
    sa.Column('panel_model', sa.String(), nullable=False),
    sa.Column('bifacial', sa.Boolean(), nullable=False),
    sa.Column('inverter_model', sa.String(), nullable=False),
    sa.Column('gcr', sa.Float(), nullable=False),
    sa.Column('shading_pct', sa.Float(), nullable=False),
    sa.Column('dc_wiring_loss_pct', sa.Float(), nullable=False),
    sa.Column('ac_wiring_loss_pct', sa.Float(), nullable=False),
    sa.Column('transformer_losses_pct', sa.Float(), nullable=False),
    sa.Column('degradation_pct', sa.Float(), nullable=False),
    sa.Column('availability_pct', sa.Float(), nullable=False),
    sa.Column('module_mismatch_pct', sa.Float(), nullable=False),
    sa.Column('lid_pct', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('run_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('annual_energy_mwh', sa.Float(), nullable=True),
    sa.Column('net_capacity_factor', sa.Float(), nullable=True),
    sa.Column('capacity_factor_dc', sa.Float(), nullable=True),
    sa.Column('capacity_factor_ac', sa.Float(), nullable=True),
    sa.Column('specific_yield', sa.Float(), nullable=True),
    sa.Column('performance_ratio', sa.Float(), nullable=True),
    sa.Column('annual_dc_nominal', sa.Float(), nullable=True),
    sa.Column('annual_snow_loss_pct', sa.Float(), nullable=True),
    sa.Column('monthly_energy', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('monthly_snow_loss', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('loss_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('timeseries_file_path', sa.String(), nullable=True),
    sa.Column('report_file_path', sa.String(), nullable=True),
    sa.Column('climate_file_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_results')
    op.drop_table('run_inputs')
    op.drop_table('runs')
    op.drop_table('sites')
    op.drop_table('customers')
    # ### end Alembic commands ###
