"""Default equipment and economic constants for layout optimization."""

# Default module: LONGi LR5-72HBD-550M
DEFAULT_MODULE_POWER_W = 551.0
DEFAULT_MODULE_AREA_M2 = 2.51
DEFAULT_MODULE_NAME = "LONGi Green Energy Technology Co. Ltd. LR5-72HBD-550M"

# Default inverter: Sungrow SG250HX-US
DEFAULT_INVERTER_NAME = "Sungrow Power Supply Co - Ltd : SG250HX-US [800V]"

# Economic defaults
DEFAULT_SOLAR_COST_PER_KW_DC = 1200.0  # $/kW
DEFAULT_SOLAR_OPEX_PER_KW_DC_YEAR = 20.0  # $/kW-DC/yr
DEFAULT_DEGRADATION_PCT = 0.5  # %/yr
DEFAULT_DISCOUNT_RATE_PCT = 7.0  # %
DEFAULT_PROJECT_LIFETIME_YEARS = 25
DEFAULT_ITC_PCT = 30.0  # %
DEFAULT_BESS_COST_PER_KWH = 340.0  # $/kWh
DEFAULT_BESS_OPEX_PER_KW_YEAR = 25.0  # $/kW/yr
DEFAULT_ENERGY_COST_ESCALATOR_PCT = 2.0  # %/yr
DEFAULT_UTILIZATION_FACTOR = 0.75

# Sweep range defaults
DEFAULT_GCR_RANGE_TRACKER = (0.30, 0.60)
DEFAULT_GCR_RANGE_FIXED = (0.40, 0.70)
DEFAULT_GCR_STEP = 0.05
DEFAULT_DCAC_RANGE = (1.15, 1.60)
DEFAULT_DCAC_STEP = 0.05
